### ISSUE TITLE
Support different realms/applications

### ISSUE THREAD

**Issue by cornelinux** [NetKnights-GmbH/privacyidea-ldap-proxy#13]
The LDAP proxy needs to identify different applications.

We could do this by identifying an extension in the LDAP URI.
Each application could add another extension.

Then we could map the extention to the realm.

The config file must allow to:

* define the extension identifier
* map application to realm.

**Comment by cornelinux** [comment]
Looking at owncloud:

1. there is a search request to find the user.
   The SearchRequest has a scope, a filter and requested attributes.
    I recommend mangling the *application* into this search request. E.g. in the filter like filtering for ``objectClass=APPLICATION`` or in the attributes.

2. the search request returns the DN of the user. The LDAP proxy could store the APPLICATION information and the DN.

3. Then we get the bindRequest of the user itself. THe problem is, that this bind request does not contain anything else, no attributes, no extensions, no filters. So *either* we use the previouly save tuple DN/APPLICATION or we would have to mangle the DN.

We could save the tuple DN/APPLICATION, which we identify with the searchRequest for a short time (some seconds), since we know, that there will be a bindRequest of this very DN shortly after.

**Comment by fredreichbier** [comment]
A remaining problem: Currently, we cannot detect that the search request belonging to a login preamble has only *one* result. I'm not yet sure how to implement this nicely.

**Comment by cornelinux** [comment]
The search *result*. Do we not see the result of the search and can't we get the length of the result?
If it is more than one, then this is not a search, that was/can be used for a next user-bind.

**Comment by fredreichbier** [comment]
Exactly :) The implementation is however a bit problematic: ldaptor's ``ProxyBase`` implements a method ``handleProxiedResponse(request, response)`` which we can use to intercept responses from the LDAP backend. In the case of search responses, it is called once for each *entry* in the search response (followed by a call with an instance of ``LDAPSearchResultDone``). So we have to count the number of invocations until ``isinstance(response, LDAPSearchResultDone)`` holds. And we need to keep the search result entry because we need to extract the DN from it. My first idea was to build a list of search result entries and to just check if ``len(lst) == 1`` when ``LDAPSearchResultDone`` is encountered. However, if we imagine an app that queries the whole directory from time to time, we would store *all* entries for *any* search request, which would be somewhat inefficient.

I implemented another approach in b25df8d
